version: "3.8"

services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_DATABASE=dashskins
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
    volumes:
      - ./data/postgres:/bitname/postgresql

volumes:
  postgres: