name: Test E2E dashskins

on: 
  push: 
    branches: "main"

jobs: 
  test-e2e: 
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: install node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: pnpm/action-setup@v3
        name: pnpm install
        with:
          version: 8
          run_install: false

      - name: get pnpm store path
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: install dependencies
        run: pnpm install

      - name: Setup posgres 
        uses: ikalnytskyi/action-setup-postgres@v5
        with:
          username: docker
          password: docker
          database: dashskins
          port: 5432
          
          
      - name: run tests e2e
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          STORAGE: ${{ secrets.STORAGE }}
        run: pnpm test:e2e  
