name: Test E2E dashskins

on:
  push: 
    branches: ["main"]
  
jobs: 
  test-e2e: 
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: install node
        uses: actions/setup-node@v4
        with:
          node-version: latest

      - uses: pnpm/action-setup@v3
        name: pnpm install
        with:
          version: 8
          run_install: false

      - name: install dependencies
        run: pnpm install

      - name: Setup posgres 
        uses: ikalnytskyi/action-setup-postgres@v5
        with:
          username: docker
          password: docker
          database: dashskins
          port: 5432
              
      - name: run tests e2e
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          STORAGE: ${{ secrets.STORAGE }}
        run: pnpm test:e2e
        
  test-unit:
    needs: test-e2e
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: install node
        uses: actions/setup-node@v4
        with:
          node-version: latest

      - uses: pnpm/action-setup@v3
        name: pnpm install
        with:
          version: 8
          run_install: false
  
      - name: install dependencies
        run: pnpm install 
      
      - name: run unit tests
        run: pnpm test
